"use client";

import { useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { scenarios, type RegionId, type RegionStatus } from "@/lib/scenarios";
import { AnnotatableRegion } from "./annotatable-region";
import { StatRowBefore, StatRowAfter } from "./stat-row";
import { InventoryTableBefore, InventoryTableAfter } from "./inventory-table";
import { ChangeHistory, type HistoryEntry } from "./change-history";

type Statuses = Record<RegionId, RegionStatus>;

function timeNow() {
  return new Date().toLocaleTimeString([], { hour: "numeric", minute: "2-digit" });
}

export function Workspace() {
  const [statuses, setStatuses] = useState<Statuses>({ stats: "idle", table: "idle" });
  const [history, setHistory] = useState<HistoryEntry[]>([]);

  const anyBusy = useMemo(
    () => Object.values(statuses).some((s) => s === "annotating" || s === "processing" || s === "reviewing"),
    [statuses],
  );
  const bothDone = statuses.stats === "done" && statuses.table === "done";

  function setStatus(id: RegionId, s: RegionStatus) {
    setStatuses((prev) => ({ ...prev, [id]: s }));
  }

  function accept(id: RegionId, prompt: string) {
    setStatus(id, "done");
    setHistory((h) => [
      { id: `${id}-${Date.now()}`, regionLabel: scenarios[id].regionLabel, prompt, time: timeNow() },
      ...h,
    ]);
  }

  function undo(id: RegionId) {
    setStatus(id, "idle");
  }

  function restart() {
    setStatuses({ stats: "idle", table: "idle" });
    setHistory([]);
  }

  return (
    <div className="mx-auto max-w-[1040px] px-6 py-10">
      <div className="grid grid-cols-1 gap-8 lg:grid-cols-[1fr_272px]">
        <div className="min-w-0">
          <div className="mb-5">
            <h1 className="text-[20px] font-medium text-ink">Inventory &amp; Orders</h1>
            <p className="mt-1 text-[14px] text-ink-soft">
              Generated by Rebolt for Ridgeline Machining Co. Hover anything below, point at what should change.
            </p>
          </div>

          <section className="mb-8">
            <AnnotatableRegion
              scenario={scenarios.stats}
              status={statuses.stats}
              onStatusChange={(s) => setStatus("stats", s)}
              beforeContent={<StatRowBefore />}
              afterContent={<StatRowAfter />}
              onAccept={(p) => accept("stats", p)}
              onUndo={() => undo("stats")}
              disabled={anyBusy && statuses.stats === "idle"}
              nudge={statuses.table === "done" ? undefined : "Nice — try the table below next."}
            />
          </section>

          <section>
            <div className="mb-2 flex items-center justify-between">
              <h2 className="text-[13px] font-medium text-ink-soft">Full inventory</h2>
              <span className="font-mono text-[11px] text-muted">9 items</span>
            </div>
            <AnnotatableRegion
              scenario={scenarios.table}
              status={statuses.table}
              onStatusChange={(s) => setStatus("table", s)}
              beforeContent={<InventoryTableBefore compact />}
              compareBefore={<InventoryTableBefore />}
              afterContent={<InventoryTableAfter scrollable />}
              compareAfter={<InventoryTableAfter />}
              onAccept={(p) => accept("table", p)}
              onUndo={() => undo("table")}
              disabled={anyBusy && statuses.table === "idle"}
              nudge={statuses.stats === "done" ? undefined : "Nice — try the summary metrics above."}
            />
          </section>
        </div>

        <aside className="lg:sticky lg:top-6">
          <div className="space-y-4">
            <AnimatePresence>
              {bothDone && (
                <motion.div
                  initial={{ opacity: 0, y: -6 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0 }}
                  className="rounded-xl border border-good/30 bg-good-soft px-4 py-3.5"
                >
                  <div className="text-[13px] font-medium text-good">2 changes shipped this session</div>
                  <p className="mt-1 text-[13px] leading-snug text-ink-soft">
                    Every edit was reviewed before it landed — nothing changed silently.
                  </p>
                  <button
                    onClick={restart}
                    className="mt-2.5 rounded-md border border-good/30 bg-surface px-2.5 py-1 text-[12px] font-medium text-good outline-none transition hover:bg-good-soft focus-visible:ring-2 focus-visible:ring-good"
                  >
                    Restart demo
                  </button>
                </motion.div>
              )}
            </AnimatePresence>

            <ChangeHistory entries={history} />
          </div>
        </aside>
      </div>
    </div>
  );
}
